### ISSUE TITLE
Mistake in switch_case_declaration.c test?

### ISSUE THREAD

**Issue by Nekketsu** [nlsandler/writing-a-c-compiler-tests#80]
Please, what is the parsing error in this test? Isn't it correct? It is tagged as `invalid_parse` but I have compiled it with `gcc` and it works correctly.

https://github.com/nlsandler/writing-a-c-compiler-tests/blob/d56ae2a50f00ab940c3024ebce4016abd9c31475/tests/chapter_8/invalid_parse/extra_credit/switch_case_declaration.c

```c
int main(void) {
    switch(3) {
        case 3:
            int i = 0;
            return i;
    }
    return 0;
}
```

**Comment by nlsandler** [comment]
The error is that the `case` label is immediately followed by a declaration, but it must be followed by a statement. GCC complains about this if you use the `-pedantic` flag: https://godbolt.org/z/8jcvceM9e. (Also worth noting: this program is legal in C23! We treat it as a parse error because we're targeting C17.)

**Comment by nlsandler** [comment]
Closing this issue, but feel free to re-open if you have follow-up questions!

**Comment by Nekketsu** [comment]
> Closing this issue, but feel free to re-open if you have follow-up questions!

Thank you very much for the explanation.
Finally, I have been able to implement it correctly according to C17.

PS: I am loving the book, thank you for all the work done!
