### ISSUE TITLE
Invalid test case testing as if valid?

### ISSUE THREAD

**Issue by SunilPaul174** [nlsandler/writing-a-c-compiler-tests#94]
```
❯ ./test_compiler compiler --chapter 9 --stage parse --bitwise --compound --increment
======================================================================
FAIL: test_invalid_semantics/break_not_in_loop (test_framework.basic.TestChapter8.test_invalid_semantics/break_not_in_loop)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/overlord/project/realpiler/writing-a-c-compiler-tests/test_framework/basic.py", line 598, in test_valid
    self.compile_success(program)
  File "/home/overlord/project/realpiler/writing-a-c-compiler-tests/test_framework/basic.py", line 365, in compile_success
    self.assertEqual(
AssertionError: compilation of /home/overlord/project/realpiler/writing-a-c-compiler-tests/tests/chapter_8/invalid_semantics/break_not_in_loop.c failed with error:
Break outside loop


----------------------------------------------------------------------
Ran 378 tests in 1.394s

FAILED (failures=1)
```

**Comment by nlsandler** [comment]
It looks like the test script is behaving correctly here. This test case is supposed to be rejected after parsing, during semantic analysis. Since you're using the `--stage parse` option, the test script only runs the compiler through the parsing stage, which should succeed for test programs in the `invalid_semantics/` subdirectories.

Off the top of my head, I would guess the issue is either:
a) Your compiler checks for breaks outside of loops during parsing, instead of a separate loop labeling stage,
or
b) Your compiler runs loop labeling even when it's passed the `--parse` option.

**Comment by SunilPaul174** [comment]
Oh ok, I didn't realize that. Yeah, I am checking for breaks outside loops in the parsing stage because i have an enum inside break to show which one it is: loop or switch. I'll close this issue now.
